config/routes.rb
Rails.application.routes.draw do
  resources :asistentes

  root "asistentes#index"

end

app/models/asistente.rb
class Asistente < ActiveRecord::Base
  FORMAS_PAGO = ["Efectivo", "Tarjeta de crédito"]

  begin :validations
    validates :nombres, presence: true
    validates :apellidos, presence: true
    validates :correo, presence: true, uniqueness: true
    validates :fecha_nacimiento, presence: true
    validates :cedula, presence: true, uniqueness: true, length: {is: 10}
    validates :direccion, presence: true
    validates :telefono, presence: true, uniqueness: true
    validates :forma_pago, presence: true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/asistentes_controller.rb
class AsistentesController < ApplicationController
  before_action :set_asistente, only: [:edit, :update, :destroy]

  def index
    @asistentes = Asistente.all
  end

  def new
    @asistente = Asistente.new
  end

  def edit
  end

  def create
    @asistente = Asistente.new(asistente_params)

    if @asistente.save
      redirect_to asistentes_url, notice: 'Asistente creado.'
    else
      render :new
    end
  end

  def update
    if @asistente.update(asistente_params)
      redirect_to asistentes_url, notice: 'Asistente actualizado.'
    else
      render :edit
    end
  end

  def destroy
    @asistente.destroy
    redirect_to asistentes_url, notice: 'Asistente eliminado.'
  end

  private

  def set_asistente
    @asistente = Asistente.find(params[:id])
  end

  def asistente_params
    params.require(:asistente).permit(:nombres, :apellidos, :correo, :fecha_nacimiento, :cedula, :direccion, :telefono, :forma_pago)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asistentes_helper.rb
module AsistentesHelper
end

app/views/asistentes/_form.html.erb
<%= form_for(@asistente) do |f| %>
  <% if @asistente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asistente.errors.count, "error", "errores") %></h2>

      <ul>
      <% @asistente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %>
    <%= f.text_field :nombres %>
  </div>
  <div class="field">
    <%= f.label :apellidos %>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :correo %>
    <%= f.email_field :correo %>
  </div>
  <div class="field">
    <%= f.label :fecha_nacimiento %>
    <%= f.date_select :fecha_nacimiento,
                      start_year: Date.today.year - 100 %>
  </div>
  <div class="field">
    <%= f.label :cedula %>
    <%= f.text_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono %>
    <%= f.phone_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :forma_pago %>
    <%= f.select :forma_pago, Asistente::FORMAS_PAGO %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asistentes/edit.html.erb
<h1>Editando Asistente</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @asistente %> |
<%= link_to 'Atrás', asistentes_path %>

app/views/asistentes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asistentes</h1>

<table>
  <caption>Listado de asistentes</caption>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Correo</th>
      <th>Fecha nacimiento</th>
      <th>Cédula</th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th>Forma pago</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @asistentes.each do |asistente| %>
      <tr>
        <td><%= asistente.nombres %></td>
        <td><%= asistente.apellidos %></td>
        <td><%= mail_to asistente.correo %></td>
        <td><%= asistente.fecha_nacimiento %></td>
        <td><%= asistente.cedula %></td>
        <td><%= asistente.direccion %></td>
        <td><%= link_to asistente.telefono, "tel:#{asistente.telefono}" %></td>
        <td><%= asistente.forma_pago %></td>
        <td><%= link_to 'Editar', edit_asistente_path(asistente) %></td>
        <td><%= link_to 'Eliminar', asistente, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Asistente', new_asistente_path %>

app/views/asistentes/new.html.erb
<h1>Nuevo Asistente</h1>

<%= render 'form' %>

<%= link_to 'Atrás', asistentes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoRegistroAsistentes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>